openapi: 3.0.0
info:
  title: ODPT Bus API
  description: バスに関連するデータを提供するAPI
  version: 0.0.0
tags: []
paths:
  /odpt:Bus:
    get:
      operationId: BusOperation_getBuses
      summary: バス車両の運行情報
      parameters:
        - name: acl:consumerKey
          in: query
          required: true
          description: 開発者サイトにて提供されるアクセストークン
          schema:
            $ref: '#/components/schemas/ConsumerKey'
          explode: false
        - name: '@id'
          in: query
          required: false
          description: データに付与された固有識別子
          schema:
            $ref: '#/components/schemas/URN'
          explode: false
        - name: owl:sameAs
          in: query
          required: false
          description: データに付与された固有識別子の別名
          schema:
            $ref: '#/components/schemas/odpt.url'
          explode: false
        - name: odpt:busroutePattern
          in: query
          required: false
          description: バス車両の運行系統のID
          schema:
            $ref: '#/components/schemas/odpt.url'
          explode: false
        - name: odpt:operator
          in: query
          required: false
          description: 事業者のID
          schema:
            $ref: '#/components/schemas/odpt.url'
          explode: false
        - name: odpt:fromBusstopPole
          in: query
          required: false
          description: 直近に通過した、あるいは停車中のバス停のID
          schema:
            $ref: '#/components/schemas/odpt.url'
          explode: false
        - name: odpt:toBusstopPole
          in: query
          required: false
          description: 次に到着するバス停のID
          schema:
            $ref: '#/components/schemas/odpt.url'
          explode: false
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bus'
        '400':
          description: パラメータ不正
        '401':
          description: acl:consumerKeyが誤っている
        '403':
          description: 権限なし
        '404':
          description: 該当データ無し
        '500':
          description: サーバー内部エラー
        '503':
          description: サービス利用不可
  /odpt:BusTimetable:
    get:
      operationId: BusTimetableOperations_getBusTimetables
      summary: バスの便の時刻表
      parameters:
        - name: acl:consumerKey
          in: query
          required: true
          description: 開発者サイトにて提供されるアクセストークン
          schema:
            $ref: '#/components/schemas/ConsumerKey'
          explode: false
        - name: '@id'
          in: query
          required: false
          description: データに付与された固有識別子
          schema:
            $ref: '#/components/schemas/URN'
          explode: false
        - name: owl:sameAs
          in: query
          required: false
          description: データに付与された固有識別子の別名
          schema:
            $ref: '#/components/schemas/odpt.url'
          explode: false
        - name: odpt:operator
          in: query
          required: true
          description: 事業者のID
          schema:
            $ref: '#/components/schemas/odpt.url'
          explode: false
        - name: odpt:busroutePattern
          in: query
          required: false
          description: 対応する系統のID
          schema:
            $ref: '#/components/schemas/odpt.url'
          explode: false
        - name: dc:title
          in: query
          required: false
          description: バス路線名称
          schema:
            type: string
          explode: false
        - name: odpt:calendar
          in: query
          required: false
          description: カレンダーのID
          schema:
            $ref: '#/components/schemas/odpt.url'
          explode: false
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BusTimetable'
        '400':
          description: パラメータ不正
        '401':
          description: acl:consumerKeyが誤っている
        '403':
          description: 権限なし
        '404':
          description: 該当データ無し
        '500':
          description: サーバー内部エラー
        '503':
          description: サービス利用不可
  /odpt:BusroutePattern:
    get:
      operationId: BusroutePatternOperations_getBusroutePatterns
      summary: 運行系統情報
      parameters:
        - name: acl:consumerKey
          in: query
          required: true
          description: 開発者サイトにて提供されるアクセストークン
          schema:
            $ref: '#/components/schemas/ConsumerKey'
          explode: false
        - name: '@id'
          in: query
          required: false
          description: データに付与された固有識別子
          schema:
            $ref: '#/components/schemas/URN'
          explode: false
        - name: owl:sameAs
          in: query
          required: false
          description: データに付与された固有識別子の別名
          schema:
            $ref: '#/components/schemas/odpt.url'
          explode: false
        - name: dc:title
          in: query
          required: false
          description: 路線・系統名称
          schema:
            type: string
          explode: false
        - name: odpt:operator
          in: query
          required: false
          description: 事業者のID
          schema:
            $ref: '#/components/schemas/odpt.url'
          explode: false
        - name: odpt:busroute
          in: query
          required: false
          description: 路線のID
          schema:
            type: string
          explode: false
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BusroutePattern'
        '400':
          description: パラメータ不正
        '401':
          description: acl:consumerKeyが誤っている
        '403':
          description: 権限なし
        '404':
          description: 該当データ無し
        '500':
          description: サーバー内部エラー
        '503':
          description: サービス利用不可
  /odpt:BusroutePatternFare:
    get:
      operationId: BusroutePatternFareOperations_getBusroutePatternFares
      summary: 運賃情報
      parameters:
        - name: acl:consumerKey
          in: query
          required: true
          description: 開発者サイトにて提供されるアクセストークン
          schema:
            $ref: '#/components/schemas/ConsumerKey'
          explode: false
        - name: '@id'
          in: query
          required: false
          description: データに付与された固有識別子
          schema:
            $ref: '#/components/schemas/URN'
          explode: false
        - name: owl:sameAs
          in: query
          required: false
          description: データに付与された固有識別子の別名
          schema:
            $ref: '#/components/schemas/odpt.url'
          explode: false
        - name: odpt:operator
          in: query
          required: false
          description: 事業者のID
          schema:
            $ref: '#/components/schemas/odpt.url'
          explode: false
        - name: odpt:fromBusstopPole
          in: query
          required: false
          description: 乗車バス停(標柱)のID
          schema:
            $ref: '#/components/schemas/odpt.url'
          explode: false
        - name: odpt:toBusstopPole
          in: query
          required: false
          description: 降車バス停(標柱)のID
          schema:
            $ref: '#/components/schemas/odpt.url'
          explode: false
        - name: odpt:ticketFare
          in: query
          required: false
          description: 切符利用時の運賃
          schema:
            type: integer
          explode: false
        - name: odpt:childTicketFare
          in: query
          required: false
          description: 切符利用時の子供運賃
          schema:
            type: integer
          explode: false
        - name: odpt:icCardFare
          in: query
          required: false
          description: ICカード利用時の運賃
          schema:
            type: integer
          explode: false
        - name: odpt:childIcCardFare
          in: query
          required: false
          description: ICカード利用時の子供運賃
          schema:
            type: integer
          explode: false
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BusroutePatternFare'
        '400':
          description: パラメータ不正
        '401':
          description: acl:consumerKeyが誤っている
        '403':
          description: 権限なし
        '404':
          description: 該当データ無し
        '500':
          description: サーバー内部エラー
        '503':
          description: サービス利用不可
  /odpt:BusstopPole:
    get:
      operationId: BusstopPoleOperations_getBusstopPoles
      summary: バス停情報
      parameters:
        - name: acl:consumerKey
          in: query
          required: true
          description: 開発者サイトにて提供されるアクセストークン
          schema:
            $ref: '#/components/schemas/ConsumerKey'
          explode: false
        - name: '@id'
          in: query
          required: false
          description: データに付与された固有識別子
          schema:
            $ref: '#/components/schemas/URN'
          explode: false
        - name: owl:sameAs
          in: query
          required: false
          description: データに付与された固有識別子の別名
          schema:
            $ref: '#/components/schemas/odpt.url'
          explode: false
        - name: dc:title
          in: query
          required: false
          description: バス停名
          schema:
            type: string
          explode: false
        - name: odpt:busstopPoleNumber
          in: query
          required: false
          description: 標柱番号
          schema:
            type: string
          explode: false
        - name: odpt:platformNumber
          in: query
          required: false
          description: のりば番号
          schema:
            type: string
          explode: false
        - name: odpt:busroutePattern
          in: query
          required: false
          description: 標柱で発着する系統のID
          schema:
            $ref: '#/components/schemas/odpt.url'
          explode: false
        - name: odpt:operator
          in: query
          required: false
          description: 事業者のID
          schema:
            $ref: '#/components/schemas/odpt.url'
          explode: false
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BusstopPole'
        '400':
          description: パラメータ不正
        '401':
          description: acl:consumerKeyが誤っている
        '403':
          description: 権限なし
        '404':
          description: 該当データ無し
        '500':
          description: サーバー内部エラー
        '503':
          description: サービス利用不可
  /odpt:BusstopPoleTimetable:
    get:
      operationId: BusstopPoleTimetableOperations_getBusstopPoleTimetables
      summary: バス停(標柱)時刻表
      parameters:
        - name: acl:consumerKey
          in: query
          required: true
          description: 開発者サイトにて提供されるアクセストークン
          schema:
            $ref: '#/components/schemas/ConsumerKey'
          explode: false
        - name: '@id'
          in: query
          required: false
          description: データに付与された固有識別子
          schema:
            $ref: '#/components/schemas/URN'
          explode: false
        - name: owl:sameAs
          in: query
          required: false
          description: データに付与された固有識別子の別名
          schema:
            $ref: '#/components/schemas/odpt.url'
          explode: false
        - name: odpt:busstopPole
          in: query
          required: false
          description: バス停(標柱)のID
          schema:
            $ref: '#/components/schemas/odpt.url'
          explode: false
        - name: odpt:busDirection
          in: query
          required: false
          description: 方面のID
          schema:
            type: string
          explode: false
        - name: odpt:busroute
          in: query
          required: false
          description: 路線のID
          schema:
            type: string
          explode: false
        - name: odpt:operator
          in: query
          required: false
          description: 事業者のID
          schema:
            $ref: '#/components/schemas/odpt.url'
          explode: false
        - name: odpt:calendar
          in: query
          required: false
          description: カレンダーのID
          schema:
            $ref: '#/components/schemas/odpt.url'
          explode: false
        - name: dc:date
          in: query
          required: false
          description: データ生成日付
          schema:
            $ref: '#/components/schemas/DateTime'
          explode: false
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BusstopPoleTimetable'
        '400':
          description: パラメータ不正
        '401':
          description: acl:consumerKeyが誤っている
        '403':
          description: 権限なし
        '404':
          description: 該当データ無し
        '500':
          description: サーバー内部エラー
        '503':
          description: サービス利用不可
security:
  - ApiKeyAuth: []
components:
  schemas:
    Bus:
      type: object
      required:
        - '@context'
        - '@id'
        - '@type'
        - owl:sameAs
        - odpt:busNumber
        - dc:date
        - dct:valid
        - odpt:frequency
        - odpt:busroutePattern
        - odpt:operator
      properties:
        '@context':
          type: string
          format: uri
          example: http://vocab.odpt.org/context_odpt_Bus.jsonld
          description: JSON-LD仕様に基づく @context のURL
        '@id':
          allOf:
            - $ref: '#/components/schemas/URN'
          example: urn:ucode:_00001C00000000000001000003533B23
          description: 固有識別子
        '@type':
          type: string
          enum:
            - odpt:Bus
          example: odpt:Bus
          description: バス運行情報のクラス名
        owl:sameAs:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.Bus:YokohamaMunicipal.02101.08_1.1889
          description: バス運行情報の固有識別子
        odpt:busNumber:
          type: string
          example: '1889'
          description: バス車両番号
        dc:date:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          example: 2024-10-28T14:17:46+09:00
          description: データ生成時刻
        dct:valid:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          example: 2024-10-28T14:18:22+09:00
          description: データ保証期限
        odpt:frequency:
          type: integer
          example: 30
          description: 更新頻度(秒)、指定された秒数以降にリクエストを行うことで、最新値が取得される。
        odpt:busroutePattern:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.BusroutePattern:YokohamaMunicipal.02101.08_1
          description: 運行中の系統のID (odpt:BusroutePatternのowl:sameAs)
        odpt:busTimetable:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.BusTimetable:YokohamaMunicipal.02101.08_1.08202410011021A00208
          description: 運行中の便の時刻表のID (odpt:BusTimetableのowl:sameAs)
        odpt:operator:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.Operator:YokohamaMunicipal
          description: 運行会社のID (odpt:Operatorのowl:sameAs)
        odpt:startingBusstopPole:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.BusstopPole:YokohamaMunicipal.SakuragichoStation.2014.6
          description: 運行中系統の始発バス停を表すID (odpt:BusstopPoleのowl:sameAs)
        odpt:terminalBusstopPole:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.BusstopPole:YokohamaMunicipal.ShidenHozonKanMae.2288.2
          description: 運行中系統の終着バス停を表すID (odpt:BusstopPoleのowl:sameAs)
        odpt:fromBusstopPole:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.BusstopPole:YokohamaMunicipal.Higashicho.5218.2
          description: 直近に通過した、あるいは停車中のバス停のID (odpt:BusstopPoleのowl:sameAs)
        odpt:fromBusstopPoleTime:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          example: 2024-10-28T14:18:20+09:00
          description: 直近に通過したバス停を発車した時刻。odpt:fromBusstopPoleがnullならばodpt:fromBusstopPoleTimeもnullとなる
        odpt:toBusstopPole:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.BusstopPole:YokohamaMunicipal.NegishiStation.4600.5
          description: 次に到着するバス停のID (odpt:BusstopPoleのowl:sameAs)
        odpt:progress:
          type: number
          example: 0
          description: Fromを0, Toを1とした際の現在位置 (割合)
        geo:long:
          type: number
          example: 139.63494873046875
          description: 対象となるバスの経度 (10進表記、測地系はWGS84)
        geo:lat:
          type: number
          example: 35.41614532470703
          description: 対象となるバスの緯度 (10進表記、測地系はWGS84)
        odpt:speed:
          type: number
          example: 0
          description: 対象となるバスの速度 (km/h)
        odpt:azimuth:
          type: number
          example: 249.9993896484375
          description: 対象となるバスの進行方向方位角を示す。単位は度(°)。北が0度で、時計回り(東回り)に増加する。
        odpt:doorStatus:
          allOf:
            - $ref: '#/components/schemas/BusDoorStatus'
          example: open
          description: 対象となるバスの扉の開閉状態
        odpt:occupancyStatus:
          allOf:
            - $ref: '#/components/schemas/OccupancyStatus'
          example: odpt.OccupancyStatus:ManySeatsAvailable
          description: 車両の混雑度
      description: |-
        バスの運行情報
        `odpt:busroutePattern` が運行中の系統を示し、 `odpt:fromBusstopPole`, `odpt:toBusstopPole` で現在位置を示す。
        接近中の判別がつかない場合は、`odpt:fromBusstopPole` は null とはならない場合がある。
        停車中の判別がつかない場合は、`odpt:toBusstopPole` は null とはならない場合がある。
        odpt:occupancyStatus は車両の混雑度を示す。
    BusDoorStatus:
      type: string
      enum:
        - open
        - close
        - self
    BusTimetable:
      type: object
      required:
        - '@context'
        - '@id'
        - '@type'
        - owl:sameAs
        - odpt:operator
        - odpt:busroutePattern
        - odpt:calendar
        - odpt:busTimetableObject
      properties:
        '@context':
          type: string
          format: uri
          example: http://vocab.odpt.org/context_odpt_BusTimetable.jsonld
          description: JSON-LD仕様に基づく @context のURL
        '@id':
          allOf:
            - $ref: '#/components/schemas/URN'
          example: urn:ucode:_00001C00000000000001000003A69FCCz
          description: 固有識別子(ucode)
        '@type':
          type: string
          enum:
            - odpt:BusTimetable
          example: odpt:BusTimetable
          description: バス時刻表のクラス名、"odpt:BusTimetable"が入る
        owl:sameAs:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.BusTimetable:OdakyuBus.Sakai91.40503.2.1400.700000677.Specific.OdakyuBus.Komae.Saturday21
          description: バス時刻表の固有識別子
        dc:date:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          example: 2024-09-11T15:04:38+09:00
          description: データ生成時刻
        dct:issued:
          allOf:
            - $ref: '#/components/schemas/Date'
          example: 2024-09-11
          description: ダイヤ改正日
        dct:valid:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          example: 2024-09-11T15:04:38+09:00
          description: データ保証期限
        dc:title:
          type: string
          example: 境９１
          description: バス路線名称(系統名等)
        odpt:kana:
          type: string
          example: さかいきゅうじゅういち
          description: バス路線名称のよみがな
        odpt:operator:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.Operator:OdakyuBus
          description: 運行会社のID (odpt:Operatorのowl:sameAs)
        odpt:busroutePattern:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.BusroutePattern:OdakyuBus.Sakai91.40503.2
          description: 対応する運行系統のID (odpt:BusroutePatternのowl:sameAs)
        odpt:calendar:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.Calendar:Specific.OdakyuBus.Komae.Saturday21
          description: カレンダーのID (odpt:Calendarのowl:sameAs)
        odpt:busTimetableObject:
          type: array
          items:
            $ref: '#/components/schemas/BusTimetableObject'
          example:
            - odpt:note: 武蔵境駅南口:10140:3
              odpt:index: 0
              odpt:canGetOn: true
              odpt:canGetOff: false
              odpt:isMidnight: false
              odpt:arrivalTime: 12:36
              odpt:busstopPole: odpt.BusstopPole:OdakyuBus.Musashisakaiekiminamiguchi.10140.3
              odpt:departureTime: 12:36
          description: バス時刻表時分情報
      description: バスの便の時刻表
    BusTimetableObject:
      type: object
      required:
        - odpt:index
        - odpt:busstopPole
      properties:
        odpt:index:
          type: integer
          example: 0
          description: 標柱通過順
        odpt:busstopPole:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.BusstopPole:OdakyuBus.Musashisakaiekiminamiguchi.10140.3
          description: バス停(標柱)のID (odpt:BusstopPoleのowl:sameAs)
        odpt:arrivalTime:
          allOf:
            - $ref: '#/components/schemas/Time'
          example: 12:36
          description: バス到着時刻
        odpt:departureTime:
          allOf:
            - $ref: '#/components/schemas/Time'
          example: 12:36
          description: バス出発時刻
        odpt:destinationSign:
          type: string
          example: ( 桜ケ丘 経由 ) 横浜駅西口 行
          description: 行先(方向幕)情報
        odpt:isNonStepBus:
          type: boolean
          example: true
          description: ノンステップバスの場合 true
        odpt:isMidnight:
          type: boolean
          example: true
          description: 深夜バスの場合 true
        odpt:canGetOn:
          type: boolean
          example: true
          description: 乗車可能な場合 true
        odpt:canGetOff:
          type: boolean
          example: true
          description: 降車可能な場合 true
        odpt:note:
          type: string
          example: 蔵境駅南口:10140:3
          description: 注記
      description: バス時刻表時分情報
    BusroutePattern:
      type: object
      required:
        - '@context'
        - '@id'
        - '@type'
        - owl:sameAs
        - dc:date
        - dc:title
        - odpt:operator
        - odpt:busstopPoleOrder
      properties:
        '@context':
          type: string
          format: uri
          example: http://vocab.odpt.org/context_odpt_BusroutePattern.jsonld
          description: JSON-LD仕様に基づく @context のURL
        '@id':
          allOf:
            - $ref: '#/components/schemas/URN'
          example: urn:ucode:_00001C0000000000000100000387F25A
          description: 固有識別子 (ucode)
        '@type':
          type: string
          enum:
            - odpt:BusroutePattern
          example: odpt:BusroutePattern
          description: バス路線情報のクラス名、"odpt:BusroutePattern"が入る
        owl:sameAs:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.BusroutePattern:NishiTokyoBus.Chokutsuu.500102.2
          description: バス路線情報の固有識別子
        dc:date:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          example: 2017-01-13T15:10:00+09:00
          description: データ生成時刻
        dct:valid:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          example: 2023-03-23T13:52:02+09:00
          description: データの保証期限
        dc:title:
          type: string
          example: 直通
          description: バス路線名称(系統名・系統番号等)
        odpt:kana:
          type: string
          example: ちょくつう
          description: バス路線名称のよみがな
        odpt:operator:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.Operator:NishiTokyoBus
          description: 運営会社を表すID (odpt:Operatorのowl:sameAs)
        odpt:busroute:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.Busroute:NishiTokyoBus.Chokutsuu
          description: 系統を表すID
        odpt:pattern:
          type: string
          example: '500102'
          description: 系統パターン
        odpt:direction:
          type: string
          example: '2'
          description: 方向
        ug:region:
          type: object
          additionalProperties: {}
          example: {}
          description: GeoJSON形式による地物情報
        odpt:busstopPoleOrder:
          type: array
          items:
            $ref: '#/components/schemas/BussstopPoleOrder'
          example:
            - odpt:busstopPole: odpt.BusstopPole:NishiTokyoBus.JRHachiojiStationNorthExit.390.15
              odpt:index: 1
              odpt:openingDoorsToGetOn:
                - odpt:OpeningDoor:FrontSide
              odpt:openingDoorsToGetOff:
                - odpt:OpeningDoor:FrontSide
          description: 停留所(標柱)の順序
        odpt:note:
          type: string
          example: 036系統::03618.03_1
          description: 注記
        odpt:busLocationURL:
          type: string
          format: uri
          description: バス位置情報を示すWebSiteのURL
      description: |-
        バス路線の系統情報
        `odpt:busstopPoleOrder` が、運行するバスの停車する停留所 (標柱) の順序を表現している。
        バス路線 ('王５７'等) は、通常、複数の系統情報から構成される。
        (e.g. 往路、復路、異なる停留所通過順のバリエーション)
    BusroutePatternFare:
      type: object
      required:
        - '@context'
        - '@id'
        - '@type'
        - owl:sameAs
        - dc:date
        - odpt:operator
        - odpt:fromBusroutePattern
        - odpt:fromBusstopPoleOrder
        - odpt:fromBusstopPole
        - odpt:toBusroutePattern
        - odpt:toBusstopPoleOrder
        - odpt:toBusstopPole
        - odpt:ticketFare
      properties:
        '@context':
          type: string
          format: uri
          example: http://vocab.odpt.org/context_odpt.jsonld
          description: JSON-LD仕様に基づく @context のURL
        '@id':
          allOf:
            - $ref: '#/components/schemas/URN'
          example: urn:ucode:_00001C00000000000001000003A7A364
          description: 固有識別子(ucode)
        '@type':
          type: string
          enum:
            - odpt:BusroutePatternFare
          example: odpt:BusroutePatternFare
          description: バス運賃のクラス名、"odpt:BusroutePatternFare"が入る
        owl:sameAs:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.BusroutePatternFare:YokohamaMunicipal.34100.09_3.25.SakuragichoStation.2014.12.YokohamaMunicipal.34100.09_3.27.YokohamaStation.7812.6
          description: バス運賃の固有識別子
        dc:date:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          example: 2024-09-28T09:14:16+09:00
          description: データ生成時刻
        dct:issued:
          allOf:
            - $ref: '#/components/schemas/Date'
          example: 2024-09-28
          description: 運賃改定日
        dct:valid:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          example: 2024-09-28T09:14:16+09:00
          description: データ保証期限
        odpt:operator:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.Operator:YokohamaMunicipal
          description: 運行会社を表すID (odpt:Operatorのowl:sameAs)
        odpt:fromBusroutePattern:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.BusroutePattern:YokohamaMunicipal.34100.09_3
          description: 乗車系統パターンを表すID (odpt:BusroutePatternのowl:sameAs)
        odpt:fromBusstopPoleOrder:
          type: integer
          example: 25
          description: 乗車停留所の系統パターン内の停留所 (標柱) 通過順。odpt:fromBusroutePattern の示す odpt:BusroutePattern の、 odpt:busstopPoleOrder の odpt:index と同じ値。
        odpt:fromBusstopPole:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.BusstopPole:YokohamaMunicipal.SakuragichoStation.2014.12
          description: 乗車バス停を表すID。odpt:fromBusroutePattern, odpt:fromBusstopPoleOrder の示すバス停 (標柱) のIDと同じ。
        odpt:toBusroutePattern:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.BusroutePattern:YokohamaMunicipal.34100.09_3
          description: 降車系統パターンを表すID (odpt:BusroutePatternのowl:sameAs)
        odpt:toBusstopPoleOrder:
          type: integer
          example: 27
          description: 降車停留所の系統パターン内の停留所 (標柱) 通過順。odpt:toBusroutePattern の示す odpt:BusroutePattern の、 odpt:busstopPoleOrder の odpt:index と同じ値。
        odpt:toBusstopPole:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.BusstopPole:YokohamaMunicipal.YokohamaStation.7812.6
          description: 降車バス停を表すID (odpt:BusstopPoleのowl:sameAs)。 odpt:toBusroutePattern, odpt:toBusstopPoleOrder の示すバス停 (標柱) のIDと同じ。
        odpt:ticketFare:
          type: integer
          example: 200
          description: 切符利用時の運賃 (円)
        odpt:childTicketFare:
          type: integer
          example: 100
          description: 切符利用時の子供運賃 (円)
        odpt:icCardFare:
          type: integer
          example: 200
          description: ICカード利用時の運賃 (円)
        odpt:childIcCardFare:
          type: integer
          example: 100
          description: ICカード利用時の子供運賃 (円)
      description: 乗車バス停(標柱)、降車バス停(標柱)についての運賃情報
    BussstopPoleOrder:
      type: object
      required:
        - odpt:busstopPole
        - odpt:index
      properties:
        odpt:busstopPole:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.BusstopPole:NishiTokyoBus.JRHachiojiStationNorthExit.390.15
          description: 停留所のID (odpt:BusstopPoleのowl:sameAs)
        odpt:index:
          type: integer
          example: 1
          description: 停留所通過順。通過順の昇順の値となる
        odpt:openingDoorsToGetOn:
          type: array
          items:
            $ref: '#/components/schemas/OpeningDoor'
          example:
            - odpt:OpeningDoor:FrontSide
          description: 乗車時に利用可能なドア
        odpt:openingDoorsToGetOff:
          type: array
          items:
            $ref: '#/components/schemas/OpeningDoor'
          example:
            - odpt:OpeningDoor:FrontSide
          description: 降車時に利用可能なドア
        odpt:note:
          type: string
          description: 注記
      description: 停留所(標柱)の順序
    BusstopPole:
      type: object
      required:
        - '@context'
        - '@id'
        - '@type'
        - owl:sameAs
        - dc:date
        - dc:title
        - odpt:operator
      properties:
        '@context':
          type: string
          format: uri
          example: http://vocab.odpt.org/context_odpt.jsonld
          description: JSON-LD仕様に基づく @context のURL
        '@id':
          allOf:
            - $ref: '#/components/schemas/URN'
          example: urn:ucode:_00001C0000000000000100000315AB88
          description: 固有識別子(ucode)
        '@type':
          type: string
          enum:
            - odpt:BusstopPole
          example: odpt:BusstopPole
          description: バス停 (標柱) のクラス名、"odpt:BusstopPole"が入る
        owl:sameAs:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.BusstopPole:OdakyuBus.Nakazato.20305.2
          description: バス停 (標柱) の固有識別子
        dc:date:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          example: 2024-08-06T14:09:17+09:00
          description: データ生成時刻
        dct:valid:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          example: 2024-08-06T14:09:17+09:00
          description: データの保証期限
        dc:title:
          type: string
          example: 中里
          description: バス停名
        odpt:kana:
          type: string
          example: ナカザト
          description: バス停名のよみがな
        title:
          allOf:
            - $ref: '#/components/schemas/MultilingualTitle'
          example:
            ja: 中里
            ja-Hrkt: とよすえきまえ
            en: Nakazato
            ko: 나카자토
            zh-Hans: 中里
          description: バス停名(多言語対応)
        geo:long:
          type: number
          example: 139.1234
          description: 標柱の経度(WGS84)
        geo:lat:
          type: number
          example: 35.1234
          description: 標柱の緯度(WGS84)
        odpt:busroutePattern:
          type: array
          items:
            $ref: '#/components/schemas/odpt.url'
          example:
            - odpt.BusroutePattern:OdakyuBus.Shimo61.20101.2
          description: 入線する系統パターンのID (odpt:BusroutePatternのowl:sameAs) のリスト
        odpt:operator:
          type: array
          items:
            $ref: '#/components/schemas/odpt.url'
          example:
            - odpt.Operator:OdakyuBus
          description: 入線するバスの運営会社を表すID (odpt:Operatorのowl:sameAs) のリスト
        odpt:busstopPoleNumber:
          type: string
          example: '2'
          description: 標柱番号。同一停留所の別標柱を区別するものであり、のりば番号とは一致する保証はない
        odpt:platformNumber:
          type: string
          example: '1'
          description: のりば番号
        odpt:busstopPoleTimetable:
          type: array
          items:
            $ref: '#/components/schemas/odpt.url'
          description: バス停(標柱)時刻表のID (odpt:BusstopPoleTimetableのowl:sameAs) のリスト
      description: バス停情報 odpt:BusstopPoleは、バス停(標柱)の情報
    BusstopPoleTimetable:
      type: object
      required:
        - '@context'
        - '@id'
        - '@type'
        - owl:sameAs
        - dc:date
        - odpt:busstopPole
        - odpt:busDirection
        - odpt:busroute
        - odpt:operator
        - odpt:calendar
      properties:
        '@context':
          type: string
          format: uri
          example: http://vocab.odpt.org/context_odpt.jsonld
          description: JSON-LD仕様に基づく @context のURL
        '@id':
          allOf:
            - $ref: '#/components/schemas/URN'
          example: urn:ucode:_00001C00000000000001000003A67D78
          description: 固有識別子(ucode)
        '@type':
          type: string
          enum:
            - odpt:BusstopPoleTimetable
          example: odpt:BusstopPoleTimetable
          description: バス停(標柱)時刻表のクラス名、"odpt:BusstopPoleTimetable"が入る
        owl:sameAs:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.BusstopPoleTimetable:KeioBus.Sakura80.Sakura88Fu.Sakura84.Sakura88.Sakura83.Higashinakano.1157.1.Minamioosawaeki.Weekday
          description: バス停(標柱)時刻表の固有識別子
        dc:date:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          example: 2024-09-30T10:42:46+09:00
          description: データ生成時刻
        dct:issued:
          allOf:
            - $ref: '#/components/schemas/Date'
          example: 2024-09-30
          description: ダイヤ改正日
        dct:valid:
          allOf:
            - $ref: '#/components/schemas/DateTime'
          example: 2024-09-30T10:42:46+09:00
          description: データ保証期限。ISO8601形式。期限が存在する場合のみ格納する。
        dc:title:
          type: string
          example: 桜８０、桜８８-ふ、桜８４、桜８８、桜８３:東中野:京王堀之内駅・相模原駅・南大沢駅・由木折返場行:平日
          description: バス路線名称(系統名等)
        odpt:busstopPole:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.BusstopPole:KeioBus.Higashinakano.1157.1
          description: バス停(標柱)を表すID (odpt:BusstopPoleのowl:sameAs)
        odpt:busDirection:
          anyOf:
            - type: string
            - type: array
              items:
                type: string
          example: odpt.BusDirection:KeioBus.Minamioosawaeki
          description: 方面を表すID。array となる場合もある。
        odpt:busroute:
          anyOf:
            - type: string
            - type: array
              items:
                type: string
          example:
            - odpt.Busroute:KeioBus.Sakura80
            - odpt.Busroute:KeioBus.Sakura88Fu
            - odpt.Busroute:KeioBus.Sakura84
            - odpt.Busroute:KeioBus.Sakura88
            - odpt.Busroute:KeioBus.Sakura83
          description: 路線を表すID。array となる場合もある。(複数路線を含む時刻表の場合等)
        odpt:operator:
          anyOf:
            - type: string
            - type: array
              items:
                type: string
          example: odpt.Operator:KeioBus
          description: 運行会社を表すID (odpt:Operatorのowl:sameAs)
        odpt:calendar:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.Calendar:Weekday
          description: 運行する曜日・日付 (odpt:Calendarのowl:sameAs)
        odpt:busstopPoleTimetableObject:
          type: array
          items:
            $ref: '#/components/schemas/BusstopPoleTimetableObject'
          example:
            - odpt:busroutePattern: odpt.BusroutePattern:KeioBus.Sakura80.699.1
              odpt:departureTime: 06:30
              odpt:destinationBusstopPole: odpt.BusstopPole:KeioBus.Minamioosawaeki.1395.0
              odpt:destinationSign: 南大沢駅
              odpt:isMidnight: true
              odpt:note: 南大沢駅行
          description: バス停(標柱)時刻表の時分情報
      description: バス停(標柱)時刻表 odpt:busstopPole で示されたバス停(標柱)の時刻表
    BusstopPoleTimetableObject:
      type: object
      required:
        - odpt:departureTime
      properties:
        odpt:arrivalTime:
          allOf:
            - $ref: '#/components/schemas/Time'
          example: 10:00
          description: バス到着時刻
        odpt:departureTime:
          allOf:
            - $ref: '#/components/schemas/Time'
          example: 10:00
          description: バス出発時刻
        odpt:destinationBusstopPole:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.BusstopPole:KeioBus.Minamioosawaeki.1395.0
          description: 行先バス停(標柱)のID (odpt:BusstopPoleのowl:sameAs)
        odpt:destinationSign:
          type: string
          example: 南大沢駅
          description: 行先(方向幕)情報
        odpt:busroutePattern:
          allOf:
            - $ref: '#/components/schemas/odpt.url'
          example: odpt.BusroutePattern:KeioBus.Sakura80.699.1
          description: バス路線のID (odpt:BusroutePatternのowl:sameAs)
        odpt:busroutePatternOrder:
          type: integer
          example: 0
          description: 系統パターン内の停留所(標柱)通過順。odpt:busroutePattern の示す odpt:BusroutePattern の odpt:busstopPoleOrder の odpt:index と同じ値。
        odpt:isNonStepBus:
          type: boolean
          example: true
          description: ノンステップバスの場合 true
        odpt:isMidnight:
          type: boolean
          example: true
          description: 深夜バスの場合 true
        odpt:canGetOn:
          type: boolean
          example: true
          description: 乗車可能な場合 true
        odpt:canGetOff:
          type: boolean
          example: true
          description: 降車可能な場合 true
        odpt:note:
          type: string
          example: 南大沢駅行
          description: 注記
      description: バス停(標柱)時刻表の時分情報
    ConsumerKey:
      type: string
      description: アクセストークン
    Date:
      type: string
      description: ISO8601 日付形式
    DateTime:
      type: string
      description: ISO8601 日付時刻形式
    MultilingualTitle:
      type: object
      required:
        - ja
        - en
      properties:
        ja:
          type: string
        en:
          type: string
        ko:
          type: string
        ja-Hrkt:
          type: string
        zh-Hans:
          type: string
      description: 多言語対応のタイトル
    OccupancyStatus:
      type: string
      enum:
        - odpt.OccupancyStatus:Empty
        - odpt.OccupancyStatus:ManySeatsAvailable
        - odpt.OccupancyStatus:FewSeatsAvailable
        - odpt.OccupancyStatus:StandingRoomOnly
        - odpt.OccupancyStatus:CrushedStandingRoomOnly
        - odpt.OccupancyStatus:FullRoomOnly
        - odpt.OccupancyStatus:NotAcceptingPassengers
    OpeningDoor:
      type: string
      enum:
        - odpt:OpeningDoor:FrontSide
        - odpt:OpeningDoor:RearSide
    Time:
      type: string
      description: ISO8601 時刻形式
    URN:
      type: string
      description: 固有識別子
    odpt.url:
      type: string
      description: 固有識別子の別名 多くが`odpt.hoge:fuga`形式
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: query
      name: acl:consumerKey
servers:
  - url: https://api.odpt.org/api/v4
    description: API サーバー
    variables: {}
